<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;netstandard2.0</TargetFrameworks>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<WarningLevel>3</WarningLevel>
		<NoWarn>1701,1702,1705,CA2254,CS1066,CS1573,CS1591,IDE0059,IDE0063,IDE0074,IDE0130</NoWarn>
		<DocumentationFile>bin/$(Configuration)/$(TargetFramework)/VIEApps.Components.Enyim.Caching.xml</DocumentationFile>
		<RootNamespace>Enyim</RootNamespace>
		<AssemblyName>VIEApps.Components.Enyim.Caching</AssemblyName>
		<AssemblyTitle>Enyim Memcached</AssemblyTitle>
		<AssemblyVersion>10.10$(ReleaseVersion)</AssemblyVersion>
		<FileVersion>10.10$(ReleaseVersion)</FileVersion>
		<InformationalVersion>10.10.$([System.DateTime]::Now.Year).$([System.DateTime]::Now.Month).$([System.DateTime]::Now.Day)@$(TargetFramework)#sn:$(Sign)#$(ReleaseRevision)</InformationalVersion>
		<Version>10.10$(ReleaseVersion)$(ReleaseSuffix)</Version>
		<Product>VIEApps NGX </Product>
		<Title>VIEApps NGX Caching</Title>
		<Description>High performance Memcached client on .NET, incorporating both synchronous and asynchronous</Description>
		<Copyright>© 2010 Attila Kiskó, © 2016 CNBlogs, © $([System.DateTime]::Now.Year) VIEApps.net</Copyright>
		<Authors>VIEApps.net</Authors>
		<Company>VIEApps.net</Company>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<SignAssembly>$(Sign)</SignAssembly>
		<AssemblyOriginatorKeyFile>../VIEApps.Components.snk</AssemblyOriginatorKeyFile>
		<DefineConstants>$(SignConstant)</DefineConstants>
		<GeneratePackageOnBuild>$(GeneratePackage)</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageId>VIEApps.Enyim.Caching$(PackageSuffix)</PackageId>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>Icon.png</PackageIcon>
		<PackageOutputPath>../</PackageOutputPath>
		<PackageTags>cache;caching;distributed;distributed-cache;memcached;enyim;enyim-memcached;enyim-caching;vieapps;vieapps.components</PackageTags>
		<PackageReleaseNotes>Support .NET 10</PackageReleaseNotes>
		<PackageProjectUrl>https://vieapps.net</PackageProjectUrl>
		<RepositoryUrl>https://github.com/vieapps/Enyim.Caching</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<None Remove=".DS_Store" />
		<None Remove=".gitattributes" />
		<None Remove=".gitignore" />
		<None Visible="false" Include="README.md" Pack="true" PackagePath="\" />
		<None Visible="false" Include="LICENSE.md" Pack="true" PackagePath="\" />
		<None Visible="false" Include="Icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
		<PackageReference Include="System.Runtime.Loader" Version="4.3.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.0" />
		<PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
		<PackageReference Include="MsgPack.Cli" Version="1.0.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.0" />
	</ItemGroup>

</Project>